/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_time_stamper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(080e48683be2b76cd5fe031e5935ee71)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <latency/pdu_time_stamper.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_time_stamper_pydoc.h>

void bind_pdu_time_stamper(py::module& m)
{

    using pdu_time_stamper = gr::latency::pdu_time_stamper;


    py::class_<pdu_time_stamper,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_time_stamper>>(
        m, "pdu_time_stamper", D(pdu_time_stamper))

        .def(py::init(&pdu_time_stamper::make),
             py::arg("key_string"),
             py::arg("name"),
             D(pdu_time_stamper, make))


        ;
}
