/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_timestamp_debug.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d53662adb695b692302abaea8b764ef8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <latency/tag_timestamp_debug.h>
// pydoc.h is automatically generated in the build directory
#include <tag_timestamp_debug_pydoc.h>

void bind_tag_timestamp_debug(py::module& m)
{

    using tag_timestamp_debug = gr::latency::tag_timestamp_debug;


    py::class_<tag_timestamp_debug,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tag_timestamp_debug>>(
        m, "tag_timestamp_debug", D(tag_timestamp_debug))

        .def(py::init(&tag_timestamp_debug::make),
             py::arg("sizeof_stream_item"),
             py::arg("key_name"),
             py::arg("name"),
             D(tag_timestamp_debug, make))


        ;
}
